adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.GameListView.as_view(), name='games'),
    re_path(r'^games/create/$', adminapp.GameCreateView.as_view(), name='game_create'),
    re_path(r'^games/edit/(?P<pk>\d+)$', adminapp.GameUpdateView.as_view(), name='game_update'),
    re_path(r'^games/del/(?P<pk>\d+)$', adminapp.GameDeleteView.as_view(), name='game_delete'),

    re_path(r'commands$', adminapp.CommandsListView.as_view(), name='commands'),
    re_path(r'^commands/create/$', adminapp.CommandCreateView.as_view(), name='command_create'),
    re_path(r'^commands/edit/(?P<pk>\d+)$', adminapp.CommandUpdateView.as_view(), name='command_update'),
    re_path(r'^commands/del/(?P<pk>\d+)$', adminapp.CommandDeleteView.as_view(), name='command_delete'),

    re_path(r'^requests$', adminapp.RequestsListView.as_view(), name='requests'),
    re_path(r'^requests/create/$', adminapp.RequestCreateView.as_view(), name='request_create'),
    re_path(r'^requests/del/(?P<pk>\d+)$', adminapp.RequestDeleteView.as_view(), name='request_delete'),

    re_path(r'^qwiz/$', adminapp.QwizListView.as_view(), name='qwiz'),
    re_path(r'^qwiz/create/$', adminapp.QwizCreateView.as_view(), name='qwiz_create'),
    re_path(r'^qwiz/edit/(?P<pk>\d+)$', adminapp.qwiz_update, name='qwiz_update'),
    re_path(r'^qwiz/del/(?P<pk>\d+)$', adminapp.QwizDeleteView.as_view(), name='qwiz_delete'),

    re_path(r'^qwestion/create/(?P<pk>\d+)$', adminapp.qwestion_create, name='qwestion_create'),
    re_path(r'^qwestion/update/(?P<pk>\d+)$', adminapp.qwestion_update, name='qwestion_update'),

    re_path('^login/$', adminapp.user_login, name='login'),
    re_path('^logout/$', adminapp.user_logout, name='logout'),
]

qwizsite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    # path('admin/', admin.site.urls),

    re_path('^$', mainapp.index, name='index'),
    re_path('^games/$', mainapp.games, name='games'),
    re_path('^galery/$', mainapp.galery, name='item'),
    re_path('^leadboard/$', mainapp.leadboard, name='leadboard'),
    re_path('^victorina/$', mainapp.victorina, name='victorina'),
    re_path('^victorina/qwestions/(?P<pk>\d+)/$', mainapp.qwestions, name='qwestion'),
    re_path('^reg/$', mainapp.registration, name='reg'),
    re_path('^reg/success/$', mainapp.success, name='success'),


    re_path('^admins/', include('adminapp.urls', namespace='admins')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import AbstractUser
from mainapp.models import SampleGame, SampleCommand, ComingRequests, SampleQwiz, Qwestions
from django import forms


class GameEditForm(forms.ModelForm):
    class Meta:
        model = SampleGame
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(GameEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class RequestEditForm(forms.ModelForm):
    class Meta:
        model = ComingRequests
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(RequestEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CommandEditForm(forms.ModelForm):
    class Meta:
        model = SampleCommand
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(CommandEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class QwizEditForm(forms.ModelForm):
    class Meta:
        model = SampleQwiz
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(QwizEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class QwestionEditForm(forms.ModelForm):
    class Meta:
        model = Qwestions
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(QwestionEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = AbstractUser
        fields = ('username', 'password')

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test
from mainapp.models import SampleGame, SampleCommand, ComingRequests, SampleQwiz, Qwestions
from adminapp.forms import GameEditForm, CommandEditForm, UserLoginForm, RequestEditForm, QwizEditForm, QwestionEditForm

from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth import authenticate, login, logout


class MyListView(ListView):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(MyListView, self).dispatch(*args, **kwargs)


class MyCreateView(CreateView):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(MyCreateView, self).dispatch(*args, **kwargs)


class MyUpdateView(UpdateView):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(MyUpdateView, self).dispatch(*args, **kwargs)


class MyDeleteView(DeleteView):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(MyDeleteView, self).dispatch(*args, **kwargs)


class GameListView(MyListView):
    model = SampleGame
    template_name = 'adminapp/games.html'


class GameCreateView(MyCreateView):
    model = SampleGame
    template_name = 'adminapp/object_create.html'
    success_url = reverse_lazy('admins:games')
    # fields = ('__all__')
    form_class = GameEditForm


class GameDeleteView(MyDeleteView):
    model = SampleGame
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admins:games')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


class GameUpdateView(UpdateView):
    model = SampleGame
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admins:games')
    form_class = GameEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'game edit'
        return context


class CommandsListView(MyListView):
    model = SampleCommand
    template_name = 'adminapp/commands.html'


# def commands(request):
#     title = 'commands'
#     commands = SampleCommand.objects.all()
#     req = ComingRequests.objects.all()
#     context = {
#         'title': title,
#         'commands': commands,
#         'requests': req,
#     }
#
#     return render(request, 'adminapp/commands.html', context)


class CommandCreateView(MyCreateView):
    model = SampleCommand
    template_name = 'adminapp/object_create.html'
    success_url = reverse_lazy('admins:commands')
    # fields = ('__all__')
    form_class = CommandEditForm


class CommandDeleteView(MyDeleteView):
    model = SampleCommand
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admins:commands')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


class CommandUpdateView(UpdateView):
    model = SampleCommand
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admins:commands')
    form_class = CommandEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'command edit'
        return context


class RequestCreateView(MyCreateView):
    model = ComingRequests
    template_name = 'adminapp/object_create.html'
    success_url = reverse_lazy('admins:requests')
    # fields = ('__all__')
    form_class = RequestEditForm


class RequestsListView(MyListView):
    model = ComingRequests
    template_name = 'adminapp/Requests.html'


class RequestDeleteView(MyDeleteView):
    model = ComingRequests
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admins:requests')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


class QwizListView(MyListView):
    model = SampleQwiz
    template_name = 'adminapp/qwizes.html'


class QwizCreateView(MyCreateView):
    model = SampleQwiz
    template_name = 'adminapp/object_create.html'
    success_url = reverse_lazy('admins:qwiz')
    # fields = ('__all__')
    form_class = QwizEditForm


@user_passes_test(lambda x: x.is_superuser)
def qwiz_update(request, pk):
    title = 'qwiz edit'
    theme = get_object_or_404(SampleQwiz, pk=pk)
    qwestions = Qwestions.objects.filter(theme=theme)

    if request.method == 'POST':
        form = QwizEditForm(request.POST, request.FILES, instance=theme)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admins:qwiz_update', args=[theme.pk]))
    else:
        form = QwizEditForm(instance=theme)

    context = {
        'title': title,
        'form': form,
        'objects': qwestions,
        'qwiz': theme,
    }

    return render(request, 'adminapp/qwiz_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def qwestion_create(request, pk):
    title = 'qwestion create'
    theme = get_object_or_404(SampleQwiz, pk=pk)

    if request.method == 'POST':
        form = QwestionEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admins:qwiz_update', args=[theme.pk]))
    else:
        form = QwestionEditForm(initial={'theme': theme})
    context = {
        'title': title,
        'form': form,
        'theme': theme,
    }
    return render(request, 'adminapp/object_create.html', context)


@user_passes_test(lambda x: x.is_superuser)
def qwestion_update(request, pk):
    title = 'qwestion edit'
    qwestion = get_object_or_404(Qwestions, pk=pk)

    if request.method == 'POST':
        form = QwestionEditForm(request.POST, request.FILES, instance=qwestion)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admins:qwiz_update', args=[qwestion.theme.pk]))
    else:
        form = QwestionEditForm(instance=qwestion)

    context = {
        'title': title,
        'form': form,
        'object': qwestion,
    }

    return render(request, 'adminapp/object_update.html', context)


class QwizDeleteView(MyDeleteView):
    model = SampleQwiz
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admins:qwiz')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


# def del_qwestion(request, pk, qpk):
#     qwestion = get_object_or_404(SampleQwiz, pk=pk)
#     qwestion.delete()
#     return HttpResponseRedirect(reverse('admin:qwiz_update', args=[qpk]))


def user_login(request):
    title = 'login'
    login_form = UserLoginForm(data=request.POST or None)
    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('index'))

    context = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'adminapp/login.html', context)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

adminapp/templates/adminapp/Requests.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="list-group">
            <span class="list-group-item list-group-item-primary">
                All requests x {{ object_list|length }}</span>
            {% for request in object_list %}
            <a href="{% url 'admins:request_delete' request.pk %}"
               class="list-group-item list-group-item-action">
                <p> {{ request.game }} :Дата</p>
                <p> {{ request.members }} х {{ request.command_name }} :Название команды</p>
                <p>{{ request.mail }} :Почта  {{ request.phone }} :Телефон</p>
                <p>{{ request.capitan_name }}:Имя капитана</p>
            </a>
            {% endfor %}
        <a href="{% url 'admins:request_create' %}" class="buttons" >NEW REQUEST</a>
        </div>
    {% endblock %}

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>
        {% block title%}
            Admin
        {% endblock %}
    </title>
    {% block css%}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock %}
    {% block js%}
    {% endblock %}
</head>

<body>
    <div class="container">
        <div class="top">
            <header>
                <a href="{% url 'index' %}"><img class="logo" src="{% static 'img/logo_blue_yellow.png' %}" alt="logo"></a>
                {% include 'adminapp/includes/inc_admin_menu.html' %}
            </header>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

adminapp/templates/adminapp/commands.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="list-group">
            <span class="list-group-item list-group-item-primary">
                All commands x {{ object_list|length }}</span>
            {% for command in object_list %}
            <a href="{% url 'admins:command_update' command.pk %}"
               class="{% if command.active %}list-group-item list-group-item-action{% else %}
               list-group-item list-group-item-secondary{% endif %}">{{ command.points }}:{{ command.name }}</a>
            <a class="del-btn" href="{% url 'admins:command_delete' command.pk %}">X</a>
            {% endfor %}
        <a href="{% url 'admins:command_create' %}" class="buttons" >NEW COMMAND</a>
        </div>
    {% endblock %}

adminapp/templates/adminapp/games.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="list-group">
            <span class="list-group-item list-group-item-primary">
                All games x {{ object_list|length }}</span>
            {% for object in object_list %}
            <a href="{% url 'admins:game_update' object.pk %}"
               class="list-group-item list-group-item-action">{{ object.name }}</a>
            <a class="del-btn" href="{% url 'admins:game_delete' object.pk %}">X</a>
            {% endfor %}
        </div>
        <a href="{% url 'admins:game_create' %}" class="buttons" >NEW GAME</a>
    {% endblock %}

adminapp/templates/adminapp/login.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="login-form">
            <form  class="fpx-4 py-3" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}">
                {% endif %}
                {{ login_form.as_p }}
                <input class="form-control" type="submit" value="login">
            </form>
        </div>
    {% endblock %}

adminapp/templates/adminapp/object_create.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="">
            <form  class="fpx-4 py-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control" type="submit" value="create">
            </form>
        </div>
    {% endblock %}

adminapp/templates/adminapp/object_delete.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="deleting">
            You want del {% if object.username %}{{ object.username }}{% else %}{{ object.name}} {% endif %}?
            <form method="post">
                {% csrf_token %}
                <input class="buttons" type="submit" value="DELETE">
            </form>
            <a href="{% url 'admins:games' %}" class="buttons">NO</a>
        </div>

    {% endblock %}

adminapp/templates/adminapp/object_update.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="login-form">
            <form  class="fpx-4 py-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control" type="submit" value="upgate">
            </form>
        </div>
    {% endblock %}

adminapp/templates/adminapp/qwiz_create.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="login-form">
            <form  class="fpx-4 py-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control" type="submit" value="upgate">
            </form>
        </div>
    {% endblock %}

adminapp/templates/adminapp/qwiz_update.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="login-form">
            <form  class="fpx-4 py-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control" type="submit" value="upgate">
            </form>
        </div>
        <a href="{% url 'admins:qwiz_delete' qwiz.pk %}" class="form-control" >delete</a>
        <div class="list-group">
            <span class="list-group-item list-group-item-primary">
                Qwestions: {{ objects|length}}</span>
            {% for object in objects %}
            <a href="{% url 'admins:qwestion_update' object.pk %}" class="{% if object.is_active %}list-group-item list-group-item-action{% else %}
            list-group-item list-group-item-secondary{% endif %}">{{ object.qwestion }}</a>
            {% endfor %}
            <a href="{% url 'admins:qwestion_create' qwiz.pk %}" class="list-group-item list-group-item-success">add qwestion</a>
        </div>
    {% endblock %}

adminapp/templates/adminapp/qwizes.html
{% extends 'adminapp/base.html'%}
{% load staticfiles %}

    {% block content %}
        <div class="list-group">
            <span class="list-group-item list-group-item-primary">
                All qwizes x {{ object_list|length }}</span>
            {% for object in object_list %}
            <div>
            <a href="{% url 'admins:qwiz_update' object.pk %}"
               class="list-group-item list-group-item-action">{{ object.name }}</a>
            </div>
            {% endfor %}
        </div>
        <a href="{% url 'admins:qwiz_create' %}" class="buttons" >NEW GAME</a>
    {% endblock %}